// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1iz4v1yFqLHf_T11Lkpw4fEw0_4J4yCQ',
    appId: '1:185921391550:android:e06ee04fe65e6266d947ef',
    messagingSenderId: '185921391550',
    projectId: 'game-islami',
    storageBucket: 'game-islami.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcBrbBLW55GubeXMWN62G-NqzGM3csunA',
    appId: '1:185921391550:ios:5dabe62ac7a846d7d947ef',
    messagingSenderId: '185921391550',
    projectId: 'game-islami',
    storageBucket: 'game-islami.appspot.com',
    iosClientId: '185921391550-l46brl6ons2r3qapjonci06r9ahc50k0.apps.googleusercontent.com',
    iosBundleId: 'com.mrezkys.gameIslami',
  );
}
